# coding=utf-8

from comply.rules.standard.guard_header import GuardHeader
from comply.rules.standard.header_in_header import HeaderInHeader
from comply.rules.standard.unified_header import UnifiedHeader
from comply.rules.standard.require_symbols import RequireSymbols
from comply.rules.standard.unused_symbol import UnusedSymbol
from comply.rules.standard.duplicate_include import DuplicateInclude
from comply.rules.standard.including_source_file import IncludingSourceFile
from comply.rules.standard.redundant_const_qualifier import RedundantConstQualifier
from comply.rules.standard.too_many_params import TooManyParams
from comply.rules.standard.inconsistent_name_placement import InconsistentNamePlacement
from comply.rules.standard.function_too_long import FunctionTooLong
from comply.rules.standard.redundant_parameter_name import RedundantParameterName
from comply.rules.standard.redundant_size_specifier import RedundantSizeSpecifier
from comply.rules.standard.unnamed_integer_parameter import UnnamedIntegerParameter
from comply.rules.standard.ambiguous_function import AmbiguousFunction
from comply.rules.standard.parameterless_function import ParameterlessFunction
from comply.rules.standard.line_too_long import LineTooLong
from comply.rules.standard.file_too_long import FileTooLong
from comply.rules.standard.tab_characters import TabCharacters
from comply.rules.standard.invisible_characters import InvisibleCharacters
from comply.rules.standard.too_many_blanks import TooManyBlanks
from comply.rules.standard.prefer_sized_integers import PreferSizedIntegers
from comply.rules.standard.todo import Todo
from comply.rules.standard.identifier_too_long import IdentifierTooLong
from comply.rules.standard.scope_too_deep import ScopeTooDeep
from comply.rules.standard.const_on_right import ConstOnRight
from comply.rules.standard.filename_contains_whitespace import FilenameContainsWhitespace
from comply.rules.standard.pad_keywords import PadKeywords
from comply.rules.standard.pad_pointers import PadPointers
from comply.rules.standard.logical_continuation import LogicalContinuation
from comply.rules.standard.missing_braces import MissingBraces
from comply.rules.standard.pad_braces import PadBraces
from comply.rules.standard.pad_commas import PadCommas
from comply.rules.standard.padded_parenthesis import PaddedParenthesis
